### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JustiFox** [target111/py-onym#1]
Hey. Can you tell me how to fix this?

> 14-May-19 00:33:39 - Starting Tellonym Spammer application.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sub
process.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sub
process.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "tellonym.py", line 111, in <module>
    main()
  File "tellonym.py", line 107, in main
    run(parse_args())
  File "tellonym.py", line 72, in run
    tellonym = Tellonym(args.user)
  File "tellonym.py", line 17, in __init__
    self.s = Service(url=PAGE_URL + self.user)
  File "C:\Users\Administrator\Desktop\py-onym-master\lib\service.py", line 21,
in __init__
    self.driver = get_driver_config()
  File "C:\Users\Administrator\Desktop\py-onym-master\config\chrome.py", line 18
, in get_driver_config
    driver = webdriver.Chrome(options=options)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\sit
e-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executabl
e needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chrome
driver/home

**Comment by target111** [comment]
Sorry for the delayed response, if you're still interested in this project and still have this issue, please follow [this guide](https://zwbetz.com/download-chromedriver-binary-and-add-to-your-path-for-automated-functional-testing/#windows) to get it working under Windows.
